# RT-003 — configure-time, fail-closed NAM LSTM overlay.
#
# WHY
#   RT-002 measured two C-heap allocations per model sample in the pinned
#   NeuralAmpModelerCore LSTM implementation. The repair is a small source patch
#   against upstream NAM (patches/nam/lstm-rt-alloc.patch). third_party/ is a
#   gitlink and must never be modified, so the patch is applied to a generated
#   copy of the pinned NAM directory inside the build tree. Every NAM
#   translation unit for the patched target is compiled from that generated
#   copy, so the patched lstm.h is the only one in play for that target.
#
# HOW (CMake-native, no mandatory external tool)
#   * SHA256 of the two pinned upstream files is declared below; mismatch aborts
#     configure (stale/forked submodule fails closed).
#   * The whole pinned NAM/ directory is copied to
#       <build>/nam-rt/generated/NAM
#     (~430 KiB of sources; Eigen/nlohmann remain the original pinned headers).
#   * Exact literal replacements are applied to the copy; each old string must
#     occur exactly once. A post-condition SHA256 of each patched file is also
#     declared, so any drift in the patch text (or upstream) aborts configure.
#   * Idempotence: file(COPY) always re-seeds the copy from the pinned original
#     before the replacements run, so reconfiguring cannot double-apply.
#
# USAGE
#   include(cmake/nam-rt/NamRtPatch.cmake)
#   nam_rt_generate_overlay("${NAM_CORE_DIR}")
#   # -> NAM_RT_INCLUDE_ROOT  : prepend to NAM include path (contains NAM/)
#   # -> NAM_RT_NAM_DIR       : generated NAM/ source directory
#
# The declared hashes are for third_party/NeuralAmpModelerCore @
# 1f42f88535884450104b8711d7595019afa0495b.

include_guard(GLOBAL)

set(NAM_RT_PIN "1f42f88535884450104b8711d7595019afa0495b")

# Pinned upstream bytes (before patching).
set(NAM_RT_LSTM_CPP_SHA256
    "c544c217c6d6e62f2f101e24145cc364ac6c91a34f9179ac81a2af2fe6963766")
set(NAM_RT_LSTM_H_SHA256
    "e66c90b9365740a2149e28f28b59ca8595ba0cac6d4ca6f588a029b3a884cec2")

# Expected generated bytes (after patching) — doubles as a patch-integrity pin.
set(NAM_RT_LSTM_CPP_PATCHED_SHA256
    "82f25497f92022edee44a62bb036bdb37490de669a766fbf0ea51ebb955151f0")
set(NAM_RT_LSTM_H_PATCHED_SHA256
    "4975a3060d7a8108c1ba27e0b15cc57ad2f0f727448459c238093368f2641bc9")

function(_nam_rt_apply_replacements file)
  file(READ "${file}" _content)

  # --- lstm.cpp: accept the non-owning hidden-state view without copying -----
  set(_sig_old
[==[void nam::lstm::LSTMCell::process_(const Eigen::VectorXf& x)]==])
  set(_sig_new
[==[void nam::lstm::LSTMCell::process_(const Eigen::Ref<const Eigen::VectorXf>& x)]==])
  string(FIND "${_content}" "${_sig_old}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "RT-003: pinned lstm.cpp process_ definition not found in ${file}")
  endif()
  string(REPLACE "${_sig_old}" "${_sig_new}" _content "${_content}")

  # --- lstm.cpp: bounded matmul (no Eigen heap temporary) --------------------
  set(_cpp_old
[==[  // The matmul
  this->_ifgo = this->_w * this->_xh + this->_b;
]==])
  set(_cpp_new
[==[  // The matmul.
  //
  // RT-003: evaluate the matrix-vector product directly into the preallocated
  // gate vector and add the bias in place. The original single expression
  // (`_w * _xh + _b`) makes Eigen materialise the product in a heap temporary
  // for this mixed matrix-vector/sum expression. Splitting it keeps the exact
  // floating-point operation order (product, then bias) while removing the
  // per-sample allocation and its matching free.
  this->_ifgo.noalias() = this->_w * this->_xh;
  this->_ifgo += this->_b;
]==])
  string(FIND "${_content}" "${_cpp_old}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "RT-003: pinned lstm.cpp matmul line not found in ${file}")
  endif()
  string(REPLACE "${_cpp_old}" "${_cpp_new}" _content "${_content}")

  set(_head_old
[==[  const Eigen::VectorXf& hidden_state = this->_layers[this->_layers.size() - 1].get_hidden_state();]==])
  set(_head_new
[==[  const Eigen::Ref<const Eigen::VectorXf> hidden_state =
    this->_layers[this->_layers.size() - 1].get_hidden_state();]==])
  string(FIND "${_content}" "${_head_old}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "RT-003: pinned lstm.cpp head hidden_state line not found in ${file}")
  endif()
  string(REPLACE "${_head_old}" "${_head_new}" _content "${_content}")

  file(WRITE "${file}" "${_content}")
endfunction()

function(_nam_rt_apply_replacements_h file)
  file(READ "${file}" _content)

  set(_get_old
[==[  /// \brief Get the current hidden state
  /// \return Hidden state vector
  Eigen::VectorXf get_hidden_state() const { return this->_xh(Eigen::placeholders::lastN(this->_get_hidden_size())); };]==])
  set(_get_new
[==[  /// \brief Get the current hidden state
  /// \return A non-owning view of the hidden-state block inside `_xh`.
  ///
  /// RT-003: this used to return `Eigen::VectorXf` by value, which allocated a
  /// heap copy on every call (once per layer hop and once for the head). The
  /// returned `Ref` maps the existing storage; callers must not keep it beyond
  /// the cell's lifetime. `process_` accepts it without copying.
  Eigen::Ref<const Eigen::VectorXf> get_hidden_state() const
  {
    return this->_xh(Eigen::placeholders::lastN(this->_get_hidden_size()));
  };]==])
  string(FIND "${_content}" "${_get_old}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "RT-003: pinned lstm.h get_hidden_state block not found in ${file}")
  endif()
  string(REPLACE "${_get_old}" "${_get_new}" _content "${_content}")

  set(_proc_old
[==[  void process_(const Eigen::VectorXf& x);]==])
  set(_proc_new
[==[  void process_(const Eigen::Ref<const Eigen::VectorXf>& x);]==])
  string(FIND "${_content}" "${_proc_old}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "RT-003: pinned lstm.h process_ declaration not found in ${file}")
  endif()
  string(REPLACE "${_proc_old}" "${_proc_new}" _content "${_content}")

  file(WRITE "${file}" "${_content}")
endfunction()

function(_nam_rt_expect_sha256 file expected label)
  file(SHA256 "${file}" _got)
  if(NOT _got STREQUAL "${expected}")
    message(FATAL_ERROR
      "RT-003: ${label} SHA256 mismatch for ${file}\n"
      "  expected ${expected}\n"
      "  got      ${_got}\n"
      "The pinned NAM revision or the overlay patch changed; refusing to build.")
  endif()
endfunction()

# nam_rt_generate_overlay(<nam_core_dir>)
#   Generates <build>/nam-rt/generated/NAM from the pinned source and applies
#   the RT-003 patch. Sets NAM_RT_INCLUDE_ROOT and NAM_RT_NAM_DIR.
function(nam_rt_generate_overlay nam_core_dir)
  set(_src "${nam_core_dir}/NAM")
  set(_root "${CMAKE_BINARY_DIR}/nam-rt/generated")
  set(_nam "${_root}/NAM")

  foreach(_f "${_src}/lstm.cpp" "${_src}/lstm.h")
    if(NOT EXISTS "${_f}")
      message(FATAL_ERROR "RT-003: missing pinned NAM file ${_f}")
    endif()
  endforeach()

  _nam_rt_expect_sha256("${_src}/lstm.cpp" "${NAM_RT_LSTM_CPP_SHA256}"
                        "pinned upstream lstm.cpp")
  _nam_rt_expect_sha256("${_src}/lstm.h" "${NAM_RT_LSTM_H_SHA256}"
                        "pinned upstream lstm.h")

  # Re-seed the generated copy from the pinned original every configure.
  file(COPY "${_src}" DESTINATION "${_root}")

  _nam_rt_expect_sha256("${_nam}/lstm.cpp" "${NAM_RT_LSTM_CPP_SHA256}"
                        "copied upstream lstm.cpp")
  _nam_rt_expect_sha256("${_nam}/lstm.h" "${NAM_RT_LSTM_H_SHA256}"
                        "copied upstream lstm.h")

  _nam_rt_apply_replacements("${_nam}/lstm.cpp")
  _nam_rt_apply_replacements_h("${_nam}/lstm.h")

  _nam_rt_expect_sha256("${_nam}/lstm.cpp" "${NAM_RT_LSTM_CPP_PATCHED_SHA256}"
                        "generated patched lstm.cpp")
  _nam_rt_expect_sha256("${_nam}/lstm.h" "${NAM_RT_LSTM_H_PATCHED_SHA256}"
                        "generated patched lstm.h")

  # Re-run configure when the pinned bytes or the patch text change. The module
  # itself is tracked automatically because it is include()d.
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_src}/lstm.cpp" "${_src}/lstm.h"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../patches/nam/lstm-rt-alloc.patch")

  set(NAM_RT_INCLUDE_ROOT "${_root}" PARENT_SCOPE)
  set(NAM_RT_NAM_DIR "${_nam}" PARENT_SCOPE)
  message(STATUS "RT-003: generated patched NAM overlay at ${_nam}")
endfunction()
