// Unit tests for jam::StyleCatalog (DEVPLAN STYLE-001, SPEC.md 13).
//
// These tests validate EVERY shipped reference against a snapshot of the ACTUAL
// compiled drum library, generated by tools/style-catalog/. That matters because
// the library has no string ids and 16 (genre, name) collisions: `("FUNK",
// "Linear funk")` is a groove at index 63 and a fill at index 187. The catalog
// therefore stores positional indices plus provenance, and the tests below fail
// if any of that drifts.

#include "JamTest.h"

#include "jam/StyleCatalog.h"

#include "../../tools/style-catalog/generated/StyleCatalogLibraryFixture.h"

#include <cstring>
#include <string>

namespace
{

using namespace jam;

/** Read-only probe over the generated snapshot of the real library. */
class FixtureProbe : public ILibraryProbe
{
public:
    int size() const noexcept override { return jamtest_style_fixture::kActualEntryCount; }

    bool lookup (LibraryIndex index, LibraryEntry& out) const noexcept override
    {
        for (int i = 0; i < jamtest_style_fixture::kActualEntryCount; ++i)
        {
            const auto& e = jamtest_style_fixture::kActualEntries[i];
            if (e.index != index)
                continue;
            out.valid = true;
            out.index = index;
            out.genre = e.genre;
            out.name = e.name;
            out.fill = e.fill;
            out.spec = e.spec;
            out.meter = Meter { e.num, e.den };
            return true;
        }
        return false;
    }
};

/** Probe that returns a deliberately mutated entry for one index. */
class CorruptingProbe : public FixtureProbe
{
public:
    CorruptingProbe (LibraryIndex index, const char* name) : index_ (index), name_ (name) {}

    bool lookup (LibraryIndex index, LibraryEntry& out) const noexcept override
    {
        if (! FixtureProbe::lookup (index, out))
            return false;
        if (index == index_)
            out.name = name_;
        return true;
    }

private:
    LibraryIndex index_;
    const char* name_;
};

const PatternProvenance* findRef (const StyleDescriptor& d, LibraryIndex index)
{
    for (int tier = 0; tier < kGrooveTierCount; ++tier)
        for (int i = 0; i < d.grooveCount[tier]; ++i)
            if (d.grooves[tier][i].index == index)
                return &d.grooves[tier][i];
    for (int kind = 0; kind < kFillKindCount; ++kind)
        for (int i = 0; i < d.fillCount[kind]; ++i)
            if (d.fills[kind][i].index == index)
                return &d.fills[kind][i];
    return nullptr;
}

int tierOf (const StyleDescriptor& d, LibraryIndex index)
{
    for (int tier = 0; tier < kGrooveTierCount; ++tier)
        for (int i = 0; i < d.grooveCount[tier]; ++i)
            if (d.grooves[tier][i].index == index)
                return tier;
    return -1;
}

} // namespace

JAM_TEST (stylecatalog, validatesEveryReferenceAgainstActualLibrary)
{
    FixtureProbe probe;
    const CatalogValidation v = StyleCatalog::validate (probe);
    CHECK (v.ok);
    CHECK_EQ (v.issues, 0);
    CHECK (v.checked > 100);
}

JAM_TEST (stylecatalog, fingerprintMatchesFrozenFixture)
{
    CHECK (std::strcmp (StyleCatalog::libraryFingerprint(),
                        jamtest_style_fixture::kLibrarySourceSha256) == 0);
    CHECK (std::strlen (StyleCatalog::libraryFingerprint()) == 64);
}

JAM_TEST (stylecatalog, shipsExactlySixNamedStyles)
{
    CHECK_EQ (StyleCatalog::count(), kStyleCount);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::Rock).shortName, "rock") == 0);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::HardRockMetal).shortName,
                        "hard-rock-metal") == 0);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::Blues).shortName, "blues") == 0);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::Funk).shortName, "funk") == 0);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::Pop).shortName, "pop") == 0);
    CHECK (std::strcmp (StyleCatalog::style (StyleId::Shuffle).shortName, "shuffle") == 0);

    StyleId found = StyleId::Pop;
    CHECK (StyleCatalog::findStyleByName ("hard-rock-metal", found));
    CHECK (found == StyleId::HardRockMetal);
    CHECK (! StyleCatalog::findStyleByName ("nope", found));
}

JAM_TEST (stylecatalog, duplicateNameTrapIsResolvedByKind)
{
    // ("FUNK","Linear funk") is a groove at 63 and a fill at 187. The catalog
    // must place each in the correct role.
    const StyleDescriptor& funk = StyleCatalog::style (StyleId::Funk);

    const PatternProvenance* asGroove = findRef (funk, 63);
    REQUIRE (asGroove != nullptr);
    CHECK (! asGroove->fill);
    CHECK (std::strcmp (asGroove->name, "Linear funk") == 0);
    CHECK (tierOf (funk, 63) == (int) GrooveTier::Medium);

    const PatternProvenance* asFill = nullptr;
    for (int kind = 0; kind < kFillKindCount && asFill == nullptr; ++kind)
        for (int i = 0; i < funk.fillCount[kind]; ++i)
            if (funk.fills[kind][i].index == 187)
                asFill = &funk.fills[kind][i];
    REQUIRE (asFill != nullptr);
    CHECK (asFill->fill);
    CHECK (std::strcmp (asFill->name, "Linear funk") == 0);
}

JAM_TEST (stylecatalog, shuffleStyleUsesDistinctDuplicateNamePatterns)
{
    // ("ROCK","Shuffle rock") appears at 9 (swing 45) and 535 (swing 33) with
    // different specs. The Shuffle style references both, at different tiers.
    const StyleDescriptor& shuffle = StyleCatalog::style (StyleId::Shuffle);
    CHECK (tierOf (shuffle, 9) == (int) GrooveTier::Medium);
    CHECK (tierOf (shuffle, 535) == (int) GrooveTier::High);

    const PatternProvenance* a = findRef (shuffle, 9);
    const PatternProvenance* b = findRef (shuffle, 535);
    REQUIRE (a != nullptr);
    REQUIRE (b != nullptr);
    CHECK (std::strcmp (a->name, "Shuffle rock") == 0);
    CHECK (std::strcmp (b->name, "Shuffle rock") == 0);
    CHECK (a->specHash != b->specHash);
}

JAM_TEST (stylecatalog, specHashHasKnownVectors)
{
    CHECK_EQ (patternSpecHash (""), 0x811C9DC5u);
    CHECK_EQ (patternSpecHash ("abc"), 0x1A47E90Bu);
}

JAM_TEST (stylecatalog, everyTierAndFillRoleIsPopulated)
{
    FixtureProbe probe;
    for (int s = 0; s < StyleCatalog::count(); ++s)
    {
        const StyleDescriptor& d = StyleCatalog::styleAt (s);
        for (int tier = 0; tier < kGrooveTierCount; ++tier)
            CHECK (d.grooveCount[tier] > 0);
        for (int kind = 0; kind < kFillKindCount; ++kind)
            CHECK (d.fillCount[kind] > 0);

        CHECK (d.meterCount > 0);
        CHECK (d.supportsMeter (Meter { 4, 4 }));
        CHECK (d.minBpm < d.idealBpm);
        CHECK (d.idealBpm <= d.maxBpm);
        CHECK (d.minRepetitionDistanceBars > 0);
    }
}

JAM_TEST (stylecatalog, everyReferenceIsUniqueWithinItsRole)
{
    for (int s = 0; s < StyleCatalog::count(); ++s)
    {
        const StyleDescriptor& d = StyleCatalog::styleAt (s);
        for (int tier = 0; tier < kGrooveTierCount; ++tier)
            for (int i = 0; i < d.grooveCount[tier]; ++i)
                for (int j = i + 1; j < d.grooveCount[tier]; ++j)
                    CHECK (d.grooves[tier][i].index != d.grooves[tier][j].index);
        for (int kind = 0; kind < kFillKindCount; ++kind)
            for (int i = 0; i < d.fillCount[kind]; ++i)
                for (int j = i + 1; j < d.fillCount[kind]; ++j)
                    CHECK (d.fills[kind][i].index != d.fills[kind][j].index);
    }
}

JAM_TEST (stylecatalog, validateDetectsCorruptedProvenance)
{
    CorruptingProbe probe (0, "Definitely not Basic");
    const CatalogValidation v = StyleCatalog::validate (probe);
    CHECK (! v.ok);
    CHECK (v.issues >= 1);
}

JAM_TEST (stylecatalog, validateDetectsMissingIndices)
{
    class EmptyProbe : public ILibraryProbe
    {
    public:
        int size() const noexcept override { return 0; }
        bool lookup (LibraryIndex, LibraryEntry&) const noexcept override { return false; }
    };

    EmptyProbe probe;
    const CatalogValidation v = StyleCatalog::validate (probe);
    CHECK (! v.ok);
    CHECK (v.issues > 0);
    CHECK (v.firstIssues[0].index != kNoLibraryEntry);
}

JAM_TEST (stylecatalog, styleOrderMatchesUiContract)
{
    // The appended main commands carry a style index 0..5 and the UI order is
    // fixed. Freeze it so an enum edit cannot silently remap the UI.
    CHECK_EQ (static_cast<int> (StyleId::Rock), 0);
    CHECK_EQ (static_cast<int> (StyleId::HardRockMetal), 1);
    CHECK_EQ (static_cast<int> (StyleId::Blues), 2);
    CHECK_EQ (static_cast<int> (StyleId::Funk), 3);
    CHECK_EQ (static_cast<int> (StyleId::Pop), 4);
    CHECK_EQ (static_cast<int> (StyleId::Shuffle), 5);
}

JAM_TEST (stylecatalog, outOfRangeStyleAccessClamps)
{
    CHECK (std::strcmp (StyleCatalog::styleAt (-5).shortName, "rock") == 0);
    CHECK (std::strcmp (StyleCatalog::styleAt (999).shortName, "rock") == 0);
    CHECK (std::strcmp (StyleCatalog::styleAt (1).shortName, "hard-rock-metal") == 0);
}
