#!/usr/bin/env python3
"""TRACK-008 report tables from the committed evidence.

Reads docs/research/tempo-stability/evidence/*.json and writes
docs/research/tempo-stability/tables.md. Pure formatting; no scoring and no
re-derivation beyond simple aggregation, so it can be regenerated at any time.
"""
import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVID = ROOT / 'docs/research/tempo-stability/evidence'
OUT = ROOT / 'docs/research/tempo-stability/tables.md'

BACKENDS = ('btrack', 'btrack-tempo-variant', 'btrack-tempo-stable', 'aubio')
SHORT_ORDER = None


def load(name):
    return json.loads((EVID / name).read_text())


def table(header, rows):
    out = ['| ' + ' | '.join(header) + ' |',
           '|' + '|'.join(['---'] * len(header)) + '|']
    for row in rows:
        out.append('| ' + ' | '.join('' if v is None else str(v) for v in row) + ' |')
    return '\n'.join(out)


def fmt(x, nd=6):
    if x is None:
        return ''
    return ('%.*f' % (nd, x)).rstrip('0').rstrip('.')


def main():
    outcomes = load('outcomes.json')
    comparisons = load('comparison.json')
    control_pairs = load('control-pairs.json')
    method = load('method-summary.json')
    coverage = load('coverage.json')
    validation = load('validation.json')

    lines = ['# TRACK-008 evidence tables', '',
             'Generated by `tools/tempo-stability/summarize.py` from the committed '
             'evidence. Missing values are empty (null), never zero.', '']

    # 1. acquisition denominators
    lines += ['## 1. Acquisition and BPM denominators', '']
    rows = []
    for corpus in ('short', 'long'):
        for backend in BACKENDS:
            cells = [o for o in outcomes if o['corpus'] == corpus and o['backend'] == backend]
            acquired = sum(1 for o in cells if o['acquired'])
            within = sum(1 for o in cells if o['acquiredWithinTwoBars'])
            locked = sum(1 for o in cells if o['hasBpmLock'])
            nom = sum(1 for o in cells if o['hasNominalBpm'])
            errs = [o['bpmRelativeError'] for o in cells if o['bpmRelativeError'] is not None]
            rows.append([corpus, backend, len(cells), acquired, within, locked, nom,
                         fmt(statistics.median(errs)) if errs else '',
                         fmt(max(errs)) if errs else ''])
    lines += [table(['corpus', 'backend', 'fixtures', 'acquired', 'within2bars', 'hasLock',
                     'hasNominal', 'bpmErrMedian', 'bpmErrWorst'], rows), '']

    # 2. long per-fixture detail (backend-specific steady windows)
    lines += ['## 2. Long matrix per fixture x backend (steady-window bounds)', '']
    rows = []
    for o in outcomes:
        if o['corpus'] != 'long':
            continue
        rows.append([o['fixture'], o['backend'],
                     int(o['acquired']), fmt(o['acquisitionBars']),
                     int(o['acquiredWithinTwoBars']), fmt(o['lockedBpm']),
                     fmt(o['bpmRelativeError']),
                     fmt(o['steadyWindowStartSeconds'], 4), fmt(o['steadyWindowEndSeconds'], 4)])
    lines += [table(['fixture', 'backend', 'acq', 'acqBars', 'within2', 'lockedBpm',
                     'bpmRelErr', 'winStart', 'winEnd'], rows), '']

    # 3. short per-fixture BPM/acquisition (compact)
    lines += ['## 3. Short matrix per fixture x backend', '']
    rows = []
    for o in outcomes:
        if o['corpus'] != 'short':
            continue
        rows.append([o['fixture'], o['backend'], int(o['acquired']),
                     fmt(o['acquisitionBars']), int(o['acquiredWithinTwoBars']),
                     fmt(o['bpmRelativeError'])])
    lines += [table(['fixture', 'backend', 'acq', 'acqBars', 'within2', 'bpmRelErr'], rows), '']

    # 4. candidate method summary (long)
    lines += ['## 4. Candidate confirmation summary (long matrix)', '']
    rows = []
    for s in method['btrack-tempo-stable']:
        if s['fixture'].endswith(('96bpm_48000hz', '126bpm_48000hz', '96bpm_44100hz', '126bpm_44100hz')):
            pass
        rows.append([s['fixture'], s['beats'], s['fallbackBeats'], s['confirmedBeats'],
                     fmt(s['firstConfirmedEventSeconds'], 4),
                     fmt(s['confirmedBpmMin'], 3), fmt(s['confirmedBpmMedian'], 3),
                     fmt(s['confirmedBpmMax'], 3), s['confirmedBeatsOutOfBand'],
                     s['longestOutOfBandConfirmedRun']])
    lines += [table(['fixture', 'beats', 'fallbackBeats', 'confirmedBeats', 'firstConfirmedEvent',
                     'confirmedMin', 'confirmedMedian', 'confirmedMax', 'outOfBand', 'longRun'],
                    rows), '']

    # 4b. old variant readiness (long)
    lines += ['## 4b. Old variant readiness summary (long matrix)', '']
    rows = []
    for s in method['btrack-tempo-variant']:
        rows.append([s['fixture'], s['beats'], s['fallbackBeats'], s['readyBeats'],
                     fmt(s['firstReadyEventSeconds'], 4),
                     fmt(s['readyBpmMin'], 3), fmt(s['readyBpmMedian'], 3),
                     fmt(s['readyBpmMax'], 3), s['readyBeatsOutOfBand'],
                     s['longestOutOfBandReadyRun']])
    lines += [table(['fixture', 'beats', 'fallbackBeats', 'readyBeats', 'firstReadyEvent',
                     'readyMin', 'readyMedian', 'readyMax', 'outOfBand', 'longRun'], rows), '']

    # 5. comparison aggregate
    lines += ['## 5. Default-vs-backend comparison aggregate', '']
    rows = []
    for corpus in ('short', 'long'):
        for other in ('btrack-tempo-variant', 'btrack-tempo-stable', 'aubio'):
            recs = [c for c in comparisons if c['corpus'] == corpus
                    and c['otherBackend'] == other]
            rows.append([corpus, other, len(recs),
                         sum(1 for c in recs if c['acquisitionGained']),
                         sum(1 for c in recs if c['acquisitionLost']),
                         sum(1 for c in recs if c['withinTwoBarsGained']),
                         sum(1 for c in recs if c['withinTwoBarsLost']),
                         sum(1 for c in recs if c['bpmErrorState'] == 'gain'),
                         sum(1 for c in recs if c['bpmErrorState'] == 'regression'),
                         sum(1 for c in recs if c['bpmErrorState'] == 'no-change'),
                         sum(1 for c in recs if c['bpmErrorState'] == 'not-evaluable')])
    lines += [table(['corpus', 'other', 'n', 'acqGain', 'acqLoss', 'w2Gain', 'w2Loss',
                     'bpmGain', 'bpmRegress', 'bpmNoChange', 'bpmNA'], rows), '']

    # 6. every regression/loss detail
    lines += ['## 6. Regressions and losses (default vs new candidate; and all others)', '']
    rows = []
    for c in comparisons:
        if (c['acquisitionLost'] or c['withinTwoBarsLost'] or c['bpmErrorState'] == 'regression'):
            rows.append([c['corpus'], c['otherBackend'], c['fixture'],
                         fmt(c['baseAcquisitionBars']), fmt(c['otherAcquisitionBars']),
                         fmt(c['baseBpmRelativeError']), fmt(c['otherBpmRelativeError']),
                         c['bpmErrorState']])
    rows.sort(key=lambda r: (r[1] != 'btrack-tempo-stable', r[0], r[2]))
    lines += [table(['corpus', 'other', 'fixture', 'baseAcqBars', 'otherAcqBars',
                     'baseBpmErr', 'otherBpmErr', 'bpmState'], rows), '']

    # 7. control pairs aggregate
    lines += ['## 7. Perturbation control pairs', '']
    rows = []
    for corpus in ('short', 'long'):
        for backend in BACKENDS:
            recs = [c for c in control_pairs if c['corpus'] == corpus and c['backend'] == backend]
            rows.append([corpus, backend, len(recs),
                         sum(1 for c in recs if c['acquisitionLost']),
                         sum(1 for c in recs if c['withinTwoBarsLost']),
                         sum(1 for c in recs if c['bpmErrorState'] == 'regression'),
                         sum(1 for c in recs if c['bpmErrorState'] == 'gain')])
    lines += [table(['corpus', 'backend', 'n', 'acqLoss', 'w2Loss', 'bpmRegress', 'bpmGain'],
                    rows), '']

    # 8. coverage aggregate
    lines += ['## 8. False-beat / silence coverage retained', '']
    rows = []
    labels = sorted({c['falseBeatCoverage'] for c in coverage})
    for corpus in ('short', 'long'):
        for backend in BACKENDS:
            cells = [c for c in coverage if c['corpus'] == corpus and c['backend'] == backend]
            rows.append([corpus, backend, len(cells),
                         sum(1 for c in cells if c['falseBeatMetricInformative']),
                         sum(1 for c in cells if c['trueSilenceMeasured']),
                         sum(1 for c in cells if c['silenceAccelerationMeasured'])]
                        + [sum(1 for c in cells if c['falseBeatCoverage'] == lb) for lb in labels])
    lines += [table(['corpus', 'backend', 'n', 'informative', 'trueSilence', 'accelMeasured']
                    + labels, rows), '']

    OUT.write_text('\n'.join(lines) + '\n')
    print('wrote %s (%d lines)' % (OUT, len(lines)))


if __name__ == '__main__':
    sys.exit(main())
